version: '3.8'
services:
  # SQL Server: Almacenará los datos geoespaciales (GEOGRAPHY) [cite: 393, 452]
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Alertify_Pass2026!

  # Redis: Funcionará como el Bus de Eventos para el procesamiento asíncrono [cite: 611, 618]
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"